CREATE TABLE APPS.XXCUS_CASH_FORECAS_STG
(
  CASF_FOECAST_ID     NUMBER,
  PROJECT_ID          NUMBER,
  TASK_ID             NUMBER,
  PERIOD              VARCHAR2(240 BYTE),
  YEAR                NUMBER,
  REV_NUM             NUMBER,
  PERIOD1             NUMBER,
  PERIOD2             NUMBER,
  PERIOD3             NUMBER,
  PERIOD4             NUMBER,
  PERIOD5             NUMBER,
  PERIOD6             NUMBER,
  PERIOD7             NUMBER,
  PERIOD8             NUMBER,
  PERIOD9             NUMBER,
  PERIOD10            NUMBER,
  PERIOD11            NUMBER,
  PERIOD12            NUMBER,
  PERIOD13            NUMBER,
  PERIOD14            NUMBER,
  PERIOD15            NUMBER,
  PERIOD16            NUMBER,
  PERIOD17            NUMBER,
  PERIOD18            NUMBER,
  LAST_UPDATE_DATE    DATE                      NOT NULL,
  LAST_UPDATED_BY     NUMBER                    NOT NULL,
  CREATION_DATE       DATE                      NOT NULL,
  CREATED_BY          NUMBER                    NOT NULL,
  LAST_UPDATE_LOGIN   NUMBER,
  STATUS_FLAG         VARCHAR2(240 BYTE),
  PO_HEADER_ID        NUMBER,
  PERIOD19            NUMBER,
  PERIOD20            NUMBER,
  PERIOD21            NUMBER,
  PERIOD22            NUMBER,
  PERIOD23            NUMBER,
  PERIOD24            NUMBER,
  PERIOD25            NUMBER,
  PERIOD26            NUMBER,
  PERIOD27            NUMBER,
  PERIOD28            NUMBER,
  PERIOD29            NUMBER,
  PERIOD30            NUMBER,
  PERIOD31            NUMBER,
  PERIOD32            NUMBER,
  PERIOD33            NUMBER,
  PERIOD34            NUMBER,
  PERIOD35            NUMBER,
  PERIOD36            NUMBER,
  PERIOD37            NUMBER,
  PERIOD38            NUMBER,
  PERIOD39            NUMBER,
  PERIOD40            NUMBER,
  PERIOD41            NUMBER,
  PERIOD42            NUMBER,
  PERIOD43            NUMBER,
  PERIOD44            NUMBER,
  PERIOD45            NUMBER,
  PERIOD46            NUMBER,
  PERIOD47            NUMBER,
  PERIOD48            NUMBER,
  PERIOD49            NUMBER,
  PERIOD50            NUMBER,
  PERIOD51            NUMBER,
  PERIOD52            NUMBER,
  PERIOD53            NUMBER,
  PERIOD54            NUMBER,
  PERIOD55            NUMBER,
  PERIOD56            NUMBER,
  PERIOD57            NUMBER,
  PERIOD58            NUMBER,
  PERIOD59            NUMBER,
  PERIOD60            NUMBER,
  PO_NUMBER           VARCHAR2(240 BYTE),
  BATCH_ID            VARCHAR2(240 BYTE),
  ERRORMSG            VARCHAR2(4000 BYTE),
  CBSLEVEL1           VARCHAR2(240 BYTE),
  CBSLEVEL1DESC       VARCHAR2(240 BYTE),
  CBSLEVEL2           VARCHAR2(240 BYTE),
  CBSLEVEL2DESC       VARCHAR2(240 BYTE),
  VENDOR_NAME         VARCHAR2(240 BYTE),
  VENDOR_SITE_CODE    VARCHAR2(240 BYTE),
  PO_CURRENCY         VARCHAR2(240 BYTE),
  RATE                NUMBER,
  PO_AMOUNT           NUMBER,
  RECEIVED_AMOUNT     NUMBER,
  BILLED_AMOUNT       NUMBER,
  AMOUNT_PAID         NUMBER,
  BALANCE_TO_PAY      NUMBER,
  ORIGINAL_BUDGET     NUMBER,
  COST_CATEGORY       VARCHAR2(240 BYTE),
  TOTAL_FORECAST      VARCHAR2(240 BYTE),
  UNCOMMITTED_BUDGET  NUMBER,
  FORECAST            NUMBER,
  VARIANCE            NUMBER,
  REVISED_FORECAST    NUMBER,
  YEAR1               NUMBER,
  YEAR2               NUMBER,
  YEAR3               NUMBER,
  TYPE                VARCHAR2(100 BYTE)
)