CREATE OR REPLACE FORCE VIEW APPS.XXMAF_CASHFORECAST_V
(
   BUDGET_VERSION_ID,
   PROJECT_ID,
   PROJ_START_DATE,
   ORG_ID,
   OU_NAME,
   BG,
   PROJ_TYPE,
   PROJ_NAME,
   PROJ_SEG,
   BUDGET_TYPE_CODE,
   VERSION_NUMBER,
   BUDGET_STATUS_CODE,
   CBS1,
   CBS1_DESC,
   TASK_ID,
   CBS2,
   CBS2DESC,
   PARENT_TASK_ID,
   BURDENED_COST_TOTAL,
   COST_CATEGORY,
   TOT_FORECAST,
   PO_NUMBER,
   VENDOR_NAME,
   VENDOR_SITE_CODE,
   PO_CREATION_DATE,
   CURRENCY_CODE,
   RATE,
   PERIOD,
   PO_AMOUNT,
   RECEIVED_AMOUNT,
   BILLED_AMOUNT,
   AMOUNT_PAID,
   BALANCE_TO_PAY
)
AS
     SELECT a.BUDGET_VERSION_ID,
            a.PROJECT_ID,
            (SELECT start_date
               FROM pa_projects_All
              WHERE project_id = a.project_id)
               proj_start_date,
            a.ORG_ID,
            a.OU_NAME,
            hr_general.DECODE_ORGANIZATION (BUSINESS_GROUP_ID) BG,
            a.PROJ_TYPE,
            a.PROJ_NAME,
            a.PROJ_SEG,
            a.BUDGET_TYPE_CODE,
            a.VERSION_NUMBER,
            a.BUDGET_STATUS_CODE,
            a.CBS1,
            a.CBS1_DESC,
            a.TASK_ID,
            a.CBS2,
            a.CBS2DESC,
            a.PARENT_TASK_ID,
            a.BURDENED_COST_TOTAL,
            a.COST_CATEGORY,
            a.TOT_FORECAST,
            --EXPENDITURE_TYPE,
            b.PO_NUMBER,
            b.VENDOR_NAME,
            b.VENDOR_SITE_CODE,
            b.PO_CREATION_DATE,
            b.CURRENCY_CODE,
            b.RATE,
            periods.period,
            SUM (b.PO_AMOUNT) PO_AMOUNT,
            --PO_AMOUNT_IN_AED,
            SUM (b.RECEIVED_AMOUNT) RECEIVED_AMOUNT,
            SUM (b.BILLED_AMOUNT) BILLED_AMOUNT,
            SUM (b.AMOUNT_PAID) AMOUNT_PAID,
            SUM (b.BALANCE_TO_PAY) BALANCE_TO_PAY
       --b.ORG_ID,
       --PROJECT_ID,
       --TASK_ID
       FROM XXMAF_BUDGET_CASH_FORECAST_V a,
            XXMAF_PO_DETLS_CF b,
            hr_operating_units hou,
            (SELECT TO_CHAR (which_month, 'Mon-yy') period
               FROM (  SELECT ADD_MONTHS (SYSDATE, ROWNUM - 1) which_month
                         FROM all_objects
                        WHERE ROWNUM <=
                                 MONTHS_BETWEEN (ADD_MONTHS (SYSDATE, 12),
                                                 ADD_MONTHS (SYSDATE, -1))
                     ORDER BY which_month)) periods
      WHERE     a.project_id = b.project_id
            AND a.task_id = b.task_id
            AND hou.organization_id = a.org_id
   GROUP BY a.BUDGET_VERSION_ID,
            a.PROJECT_ID,
            a.ORG_ID,
            a.OU_NAME,
            a.PROJ_TYPE,
            a.PROJ_NAME,
            a.PROJ_SEG,
            a.BUDGET_TYPE_CODE,
            a.VERSION_NUMBER,
            a.BUDGET_STATUS_CODE,
            a.CBS1,
            a.CBS1_DESC,
            a.TASK_ID,
            a.CBS2,
            a.CBS2DESC,
            a.PARENT_TASK_ID,
            a.BURDENED_COST_TOTAL,
            a.COST_CATEGORY,
            a.TOT_FORECAST,
            --EXPENDITURE_TYPE,
            b.PO_NUMBER,
            b.VENDOR_NAME,
            b.VENDOR_SITE_CODE,
            b.PO_CREATION_DATE,
            b.CURRENCY_CODE,
            b.RATE,
            hou.BUSINESS_GROUP_ID,
            periods.period;